spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://192.168.31.163/sell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost/ipinche?characterEncoding=utf-8&useSSL=false
  jpa:
      show-sql: true